### ISSUE TITLE
Inspection failed

### ISSUE THREAD

**Issue by rdebath** [RichardJCase/KernelScript#1]
I haven't compiled it, but this hello would fail.
``` bf
++++[>++++<-]>[>++>[++++++++>]+[<]>-]
>>>>>>>>-.<<<++++.<+++..<--.<<.>>>>>--.<<<.+++.>.>-.>>>>>>>>.>>>+.
```

Loops should be `while do` not `repeat ... until not`

**Comment by RichardJCase** [comment]
Thanks. Working on getting it to compile on my machine first, then I'll have a look at it.

**Comment by RichardJCase** [comment]
Fixed the issue.
